language: android
android:
  components:
  - build-tools-28.0.3
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-27
  - sys-img-x86-android-19
before_install:
- openssl aes-256-cbc -K $encrypted_89893b5696d4_key -iv $encrypted_89893b5696d4_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
